<?php


define( 'SMUZFORM_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

define( 'SMUZFORM_PLUGIN_URL', plugins_url( '',plugin_basename( __FILE__ ) ) );

define( 'SMUZFORM_PLUGIN_DIR_NAME', dirname( plugin_basename( __FILE__ ) ) );

define( 'SMUZFORM_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME', 'admin/includes' );

define( 'SMUZFORM_PLUGIN_INCLUDE_PUBLIC_DIRECTORY_NAME', 'public/includes' );

define( 'SMUZFORM_PLUGIN_VIEW_DIRECTORY_NAME', 'views' );

define( 'SMUZFORM_PLUGIN_CSS_DIRECTORY_NAME', 'css' );

define( 'SMUZFORM_PLUGIN_JS_DIRECTORY_NAME', 'js' );

define( 'SMUZFORM_PLUGIN_ADMIN_DIRECTORY', SMUZFORM_PLUGIN_PATH . 'admin' . DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_PUBLIC_DIRECTORY', SMUZFORM_PLUGIN_PATH . 'public' . DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_INCLUDE_ADMIN_DIRECTORY', SMUZFORM_PLUGIN_PATH .
									  	SMUZFORM_PLUGIN_INCLUDE_ADMIN_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_VIEW_DIRECTORY', SMUZFORM_PLUGIN_PATH .
									  	SMUZFORM_PLUGIN_VIEW_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_CSS_DIRECTORY', SMUZFORM_PLUGIN_PATH .
									  	SMUZFORM_PLUGIN_CSS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_JS_DIRECTORY', SMUZFORM_PLUGIN_PATH .
									  	SMUZFORM_PLUGIN_JS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SMUZFORM_PLUGIN_MAIN_FILE', SMUZFORM_PLUGIN_PATH . 'forms.php' );

define( 'SMUZFORM_SHORTCODE', 'sform' );

define( 'SMUZFORM_UPLOAD_DIR_NAME', 'smuzformfiles-' );

define( 'SMUZFORM_PLUGIN_VERSION', '1.4' );

define( 'SMUZFORM_ENTRIES_PER_PAGE', 10 );

define( 'SMUZFORM_ENTRY_DATABASE_TABLE_NAME', 'smuzform_entry' );

define( 'SMUZFORM_ENTRY_DATA_DATABASE_TABLE_NAME', 'smuzform_entry_data' );


//Errors
define( 'SMUZFORM_ERROR_FIELD_REQUIRED', 10 );

define( 'SMUZFORM_ERROR_FIELD_MINIMUM_LENGTH', 20 );

define( 'SMUZFORM_ERROR_FIELD_MAXIMUM_LENGTH', 30 );

define( 'SMUZFORM_ERROR_FIELD_NO_DUPLICATE', 40 );

define( 'SMUZFORM_ERROR_FIELD_NUMBER_MINIMUM_LENGTH', 50 );

define( 'SMUZFORM_ERROR_FIELD_NUMBER_MAXIMUM_LENGTH', 60 );

define( 'SMUZFORM_ERROR_FIELD_TEXTAREA_MINIMUM_LENGTH', 70 );

define( 'SMUZFORM_ERROR_FIELD_TEXTAREA_MAXIMUM_LENGTH', 80 );

define( 'SMUZFORM_ERROR_FIELD_NOT_NUMERIC', 90 );

define( 'SMUZFORM_ERROR_FIELD_NOT_EMAIL', 100 );

define( 'SMUZFORM_ERROR_FIELD_INVALID_DATE', 110 );

define( 'SMUZFORM_ERROR_FIELD_NOT_URL', 120 );